'use strict';
/* SciSpark — Learning Starting Point Check · question bank (EN V2)
   3 year-level sets (Y7 / Y8 / Y9), 15 questions each.
   Q1–Q13 = MCQ, auto-graded (correct = 0-based index). Max score = 13.
   Q14–Q15 = short answer, NOT scored (collected for the teacher).
   Content + correct answers are strategist-locked — do not edit the science. */

const INTAKE_SETS = {
  Y7: [
    { type:'mcq', q:'What is a habitat?',
      options:['how they breathe','how they feed','what they eat','where they live'], correct:3 },
    { type:'mcq', q:'Which of these is a liquid?',
      options:['ice','water','steam','wood'], correct:1 },
    { type:'mcq', q:'Which of these is a metal?',
      options:['wood','plastic','iron','glass'], correct:2 },
    { type:'mcq', q:'What is the name of the force that pulls things down to the Earth?',
      options:['push','pull','friction','gravity'], correct:3 },
    { type:'mcq', q:'Which material is a good conductor of electricity?',
      options:['plastic','wood','copper','rubber'], correct:2 },
    { type:'mcq', q:'All food chains start with a producer. Which organism cannot start a food chain?',
      options:['animal','grass','plant','tree'], correct:0 },
    { type:'mcq', q:'A carnivore is an animal that eats:',
      options:['only plants','only meat','plants and meat','nothing'], correct:1 },
    { type:'mcq', q:'Which change can be reversed?',
      options:['burning wood','cooking an egg','melting ice','baking a cake'], correct:2 },
    { type:'mcq', q:'A circuit has one cell, one lamp and wires. Which change makes the lamp brighter?',
      options:['add another cell','add another lamp','make wires longer','take away the cell'], correct:0 },
    { type:'mcq', q:'We have day and night because:',
      options:['the Sun moves around the Earth','the Earth spins on its axis','the Moon blocks the Sun','clouds cover the sky'], correct:1 },
    { type:'mcq', q:'Food chain: grass → impala → cheetah. Which animal is the predator?',
      options:['grass','impala','cheetah','all of them'], correct:2 },
    { type:'mcq', q:'Penguins live in very cold places. What helps them stay warm?',
      options:['thin skin','thick layer of fat','wet feathers','bare feet'], correct:1 },
    { type:'mcq', q:'How long does the Earth take to go around the Sun once?',
      options:['1 day','1 month','1 year','24 hours'], correct:2 },
    { type:'short', q:'In one sentence: what is a “reversible change”?' },
    { type:'short', q:'In one sentence: why do we have day and night?' }
  ],

  Y8: [
    { type:'mcq', q:'Which gas enters the body when a person breathes in?',
      options:['oxygen','carbon dioxide','water vapour','smoke'], correct:0 },
    { type:'mcq', q:'A material that allows light to pass through clearly is called:',
      options:['opaque','transparent','magnetic','insoluble'], correct:1 },
    { type:'mcq', q:'A substance that can dissolve in water is:',
      options:['opaque','insoluble','soluble','magnetic'], correct:2 },
    { type:'mcq', q:'Which force pulls objects towards the Earth?',
      options:['gravity','friction','air resistance','reflection'], correct:0 },
    { type:'mcq', q:'Which unit is used to measure weight?',
      options:['kg','N','cm³','m'], correct:1 },
    { type:'mcq', q:'Which system breaks down food into nutrients?',
      options:['digestive','circulatory','nervous','respiratory'], correct:0 },
    { type:'mcq', q:'A pure substance made from only one type of atom is an:',
      options:['element','compound','mixture','solution'], correct:0 },
    { type:'mcq', q:'Which nutrient is mainly needed for growth and repair of body tissues?',
      options:['protein','water','fibre','vitamin C'], correct:0 },
    { type:'mcq', q:'Which statement about particles in a solid is correct?',
      options:['far apart and move freely','vibrate about fixed positions','fill any container','cannot move at all'], correct:1 },
    { type:'mcq', q:'If a road surface becomes rougher, friction usually:',
      options:['increases','decreases','becomes zero','turns into gravity'], correct:0 },
    { type:'mcq', q:'Look at the organisms. Which organism is a producer?',
      options:['grass','grasshopper','toad','hawk'], correct:0 },
    { type:'mcq', q:'A truck has a driving force of 100 N forwards and a resistance force of 60 N backwards. What happens to the truck?',
      options:['It speeds up','It stays still','It moves backwards','It floats upwards'], correct:0 },
    { type:'mcq', q:'Steel is an alloy. It contains carbon and iron. Steel is:',
      options:['an atom','an element','a compound','a mixture'], correct:3 },
    { type:'short', q:'In one sentence: what does “soluble” mean?' },
    { type:'short', q:'In one sentence: why does a rougher surface give more friction?' }
  ],

  Y9: [
    { type:'mcq', q:'Which word means not reactive?',
      options:['explosive','soluble','inert','acidic'], correct:2 },
    { type:'mcq', q:'Which word describes how high or low a sound is?',
      options:['pitch','volume','echo','vibration'], correct:0 },
    { type:'mcq', q:'Which method is used to separate an insoluble solid from a liquid?',
      options:['filtration','evaporation','freezing','melting'], correct:0 },
    { type:'mcq', q:'Which word describes a substance made of only one type of atom?',
      options:['element','compound','mixture','solution'], correct:0 },
    { type:'mcq', q:'Which word describes a group of organisms that can reproduce and produce fertile offspring?',
      options:['habitat','species','population','community'], correct:1 },
    { type:'mcq', q:'Which word describes the height of a wave and is linked to how loud a sound is?',
      options:['frequency','amplitude','wavelength','reflection'], correct:1 },
    { type:'mcq', q:'Which method can be used to get salt crystals from salt water?',
      options:['filtration','evaporation','magnetism','chromatography'], correct:1 },
    { type:'mcq', q:'A sound wave has a higher frequency than another sound wave. What happens to the pitch?',
      options:['lower','higher','stops','becomes a solid'], correct:1 },
    { type:'mcq', q:'In the model of an atom, why do electrons stay near the nucleus?',
      options:['positive nucleus attracts negative electrons','negative nucleus attracts positive electrons','electrons are neutral, so they cannot move away','nucleus and electrons same charge, so attract'], correct:0 },
    { type:'mcq', q:'Which order shows biological organisation from smallest to largest?',
      options:['cell → tissue → organ','organ → tissue → cell','tissue → cell → organ','organ → cell → tissue'], correct:0 },
    { type:'mcq', q:'She heats one end of a copper rod and an iron rod. The pin on the copper rod falls first, the iron rod later. What does this show?',
      options:['Copper is a better thermal conductor than iron','Iron is a better thermal conductor than copper','Copper has a lower temperature than iron','Iron does not transfer thermal energy'], correct:0 },
    { type:'mcq', q:'Paper chromatography separates ink into several coloured spots. Why does this happen?',
      options:['Different dyes move up the paper at different speeds','The paper changes the dyes into new substances','All dyes move the same distance','The solvent destroys the dyes'], correct:0 },
    { type:'mcq', q:'At the top of a high mountain, air pressure is much lower. Why does low air pressure make breathing more difficult?',
      options:['Fewer air particles, so less oxygen taken in with each breath','The lungs stop making oxygen','The air contains more CO2 than oxygen, so respiration stops','Oxygen particles become too large to enter the alveoli'], correct:0 },
    { type:'short', q:'In one sentence: what does “inert” mean?' },
    { type:'short', q:'In one sentence: why does a higher frequency give a higher pitch?' }
  ]
};
